### PR TITLE
Redirect to new location

### PR DESCRIPTION
**Pull request by Teebusch**
The documents are now maintained in the website repository. We can archive this one, but maybe we should leave a "content has moved" note. See https://github.com/uio-carpentry/uio-carpentry.github.io/issues/36

Question: should we remove everything but the README, or leave the (potentially outdated) charter and mission statement here?

### CODE REVIEW

**Comment by lexnederbragt** [comment]
I would say, for now, to replace everything with a pointer to the new location in case someone uses a direct link to one of the pages (how unlikely that may be).

**Comment by Teebusch** [comment]
> I would say, for now, to replace everything with a pointer to the new location in case someone uses a direct link to one of the pages (how unlikely that may be).

Ok, I've removed everytihn but the readme now.

**Comment by lexnederbragt** [comment]
I think that be deleting index.rst, https://governance.readthedocs.io/en/latest/index.html will throw a 404. Maybe copy the content from the readme file to index.rst?

**Comment by Teebusch** [comment]
Oh, you plan to keep the readthedocs site. In that case we might have to keep more files than just index.rst... not sure. I have two check how readthedocs.org works

**Comment by lexnederbragt** [comment]
Closing in favour of #29 (Hope that's OK...).

**Pull request closed without merging**
